import React from 'react';
import "./about.css";
import clone1 from "../../assets/image1.png";
import ellipse1 from "../../assets/ellipse1.png";
import frame from "../../assets/frame.png";
import spline1 from "../../assets/spline1.png";
import clone2 from "../../assets/image2.png";
import ellipse2 from "../../assets/ellipse2.png";
import spline2 from "../../assets/spline2.png";

const About = () => {
  return (
    <div className='nft__about' id='about'>
      <div className='nft__about-heading'>
        <h1>
          A new wave of collectibles is about to hit the blockchain.
        </h1>
        <p>
          Characterised by soft lighting, vintage colour schemes and quirky costumes, these generative 3D TinyFaces are the addition to your NFT collection you’ve been waiting for.
        </p>
      </div>
      <div className='nft__about-content1'>
        <div className='nft__about-content1__img'>
          <img src={ellipse1} alt="ellipse1" className='ellipse1'/>
          <img src={frame} alt="frame" className='frame'/>
          <img src={clone1} alt="clone1" className='clone1'/>
          <img src={spline1} alt="spline1" className='spline1' />
        </div>
        <div className='nft__about-content1__about'>
          <h6>About</h6>
          <h3>Thousands of unique NFTs</h3>
          <p>Each character is entirely unique and is generated by combining attributes such as colour palettes, skin tones, facial traits, outfits and accessories. With nearly endless combinations, all characters are guaranteed to be one of a kind.</p>
          <button type='button'>Place a bid</button>
        </div>  
      </div>
      <div className='nft__about-content2'>
        <div className='nft__about-content1__about'>
          <h6>About</h6>
          <h3>Secure the most rare</h3>
          <p>Even though no two Tinyfaces will ever be the same, some variations are rarer than others. Watch out for special accessories and raw materials - the rarer the attributes, the rarer your character will be.</p>
          <button type='button'>Place a bid</button>
        </div> 
        <div className='nft__about-content2__img'>
          <img src={ellipse2} alt="ellipse1" className='ellipse2'/>
          <img src={frame} alt="frame" className='frame'/>
          <img src={clone2} alt="clone1" className='clone2' />
          <img src={spline2} alt="spline1" className='spline2' />
        </div> 
      </div>
      
    </div>
  )
}

export default About